name: CI

on:
  push:
    branches: [ main, 17.0, 18.0 ]
  pull_request:
    branches: [ main, 17.0, 18.0 ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint-odoo black isort
    - name: Run Black
      run: black --check --diff . || true
    - name: Run isort
      run: isort --check-only --diff . || true
    - name: Run Pylint
      run: pylint-odoo --rcfile=.pylintrc . || true
